repos:
  - repo: "https://github.com/prettier/prettier"
    rev: 1.17.0
    hooks:
      - id: prettier

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.23.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-json
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 4.3.20
  #   hooks:
  #     - id: isort
