version: "3.6"
services:
  stripe-subscriptions-migrator:
    build:
      context: .
    image: stripe-subscriptions-migrator
    env_file:
      - ./env-docker
    working_dir: /app
    entrypoint: bash
    volumes:
      - .:/app
